## Numpy array and basics

learn about numpy

In [2]:
import numpy as np
import time

## creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print(f"arr_1d : {arr_1d}")


arr_2d = np.array([[1,2,3], [4,5,6]])
print(f"arr_2d : {arr_2d}")

arr_1d : [1 2 3 4 5]
arr_2d : [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3,4,5]
print("python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3,4,5])  ## element wise multiplication
print("python array multiplication: ", np_array * 2)


start = time.time()
py_list = [i*2 for i in range(10000)]
print("\n List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(10000) * 2
print("\n Numpy operation time: ", time.time() - start)



python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array multiplication:  [ 2  4  6  8 10]

 List operation time:  0.0005216598510742188

 Numpy operation time:  0.00019812583923339844


### creatin array from scratch  

In [22]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((3,4))
print("\nOnes array: \n",ones)

full = np.full((2,2), 7)
print("\nConstants array: \n",full)

random = np.random.random((2,3))
print("\nRandoms array: \n", np.floor(random * 10))

sequence = np.arange(0, 10, 2)
print("\nSequence array: \n",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Constants array: 
 [[7 7]
 [7 7]]

Randoms array: 
 [[5. 8. 2.]
 [2. 7. 6.]]

Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix, Tensor

In [28]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],
                    [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape of array: ", arr.shape)
print("Dimension of array: ", arr.ndim)
print("Size of array: ", arr.size)
print("Dtype of array: ", arr.dtype)

Shape of array:  (2, 3)
Dimension of array:  2
Size of array:  6
Dtype of array:  int64


### Array reshaping

In [ ]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: \n", reshaped)

flatened = reshaped.flatten()
print("\n Flatened array: \n", flatened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: \n", raveled)

# Transpose
transposed = reshaped.T
print("\n Transpose array: \n", transposed)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
