## Numpy Array Operations

In [4]:
import numpy as np

In [5]:
arr = np.arange(1, 11)
print("Basic Slicing: ", arr[2:7])
print("With Step Slicing: ", arr[1:8:2])
print("Negative Slicing: ", arr[-1])

Basic Slicing:  [3 4 5 6 7]
With Step Slicing:  [2 4 6 8]
Negative Slicing:  10


In [6]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("specific element: ", arr_2d[1, 1])
print("Whole Row: ", arr_2d[0])
print("Whole Column: ", arr_2d[:, 0])

specific element:  5
Whole Row:  [1 2 3]
Whole Column:  [1 4 7]


## Sorting

In [7]:
unsorted_arr = np.array([3, 4,1 ,4, 16, 15, 0, -13, 523, 25])
print("Sorted array: ", np.sort(unsorted_arr))

arr_2d_unsorted = np.array([[3, 1], [10, 5], [2, 3]])
print("Sorted 2d by column: \n", np.sort(arr_2d_unsorted, axis = 0))

Sorted array:  [-13   0   1   3   4   4  15  16  25 523]
Sorted 2d by column: 
 [[ 2  1]
 [ 3  3]
 [10  5]]


## Filter

In [8]:
numbers = np.arange(1,11)
even_num = numbers[numbers % 2 == 0]
print("even numbers: ", even_num)

even numbers:  [ 2  4  6  8 10]


## Fliter with Mask

In [9]:
mask = numbers > 5
print("numbers greater than 5: ", numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where

In [10]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("using np.where(): ", numbers[where_result])

[1 3 5]
using np.where():  [ 6  7  8  9 10]


In [12]:
condition_arr = np.where(numbers > 5, "true", "false")
print(condition_arr)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing Data

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

merged = np.concatenate((arr1, arr2))
print(merged)

[5 7 9]
[1 2 3 4 5 6]


### Array Complatibility

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibilty Shapes: ", a.shape == b.shape)

Compatibilty Shapes:  True


In [27]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

# vstack always adds a row
with_new_row = np.vstack((original, new_row))
print("original: \n", original)
print("with new row: \n", with_new_row)

# hstack column add krta hai
new_column = np.array([[7], [8], [9]])
with_new_col = np.hstack((with_new_row, new_column))
print("with new column: \n", with_new_col)


original: 
 [[1 2]
 [3 4]]
with new row: 
 [[1 2]
 [3 4]
 [5 6]]
with new column: 
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [29]:
arr = np.array([1, 2,3 ,4 ,5])
deleted = np.delete(arr, 2)

print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
